### ISSUE TITLE
[Bug]: test1

### ISSUE THREAD

**Issue by YoJayz** [lmx1117/test#1]
### Prerequisite

- [X] Make sure you have [searched](https://github.com/openblocks-dev/openblocks/issues) duplicate or closed issues before.

### Environment

- Device: [e.g. Laptop]
- OS: [e.g. macOS 12, Windows 10, Ubuntu 20.04, IOS]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. Cloud / Self Hosted - ]

### Description

1. 23232
2. wssw
3. sssss

### Reproduce

1. click 
2. w2w22

**Comment by lmx1117** [comment]
111
